Proper error message for empty config
If `config/paypal.yml` is empty then `YAML.load` will return `false` on empty string.
Actual error in this case: `NoMethodError: undefined method `[]' for false:FalseClass`

By returning empty hash instead of `false` value from `read_configurations` method we're getting such error message:
`Paypal::SDK::Core::Exceptions::MissingConfig: Configuration[development] NotFound`